server:
  port: 8020
  servlet:
    context-path: /api/stock

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.dhl.fin.api.dao: debug

grpc:
  client:
    FINTP:
      address: static://localhost:3456
      negotiation-type: PLAINTEXT
  server:
    port: 3456

spring:
  # 当前环境
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false
  redis:
    # Enable SSL support
    ssl: false
    # Connection timeout in milliseconds
    timeout: 5000
  #附件上传大小限制
  servlet:
    multipart:
      enabled: true
      maxFileSize: 50MB
      maxRequestSize: 50MB
  mail:
    host: smtp.cn.dhl.com
    port: 25
    default-encoding: utf-8
    protocol: smtp
  freemarker:
    template-loader-path: classpath:/template
    suffix: .ftl

local:
  rpmp:
    appId: FA15ACB2-6842-48A4-A380-DECE82C6B417
    # 用户登录过期时间。单位：天
    sessionExpiredDay: 30
    # 允许匿名访问的 com.dhl.fin.api, 逗号分隔
    allowAnonymousApiList: >-
      /login/login
    internalAuth:
      enable: false
      apiList: /com.dhl.fin.api/internal/**
    appCredential:
      # 使用 access key 和 signature 签名验证的 com.dhl.fin.api，逗号分隔
      apiList: /com.dhl.fin.api/ak/**
      signatureExpiredMs: 60000
    token:
      key: FWSZFCJVBKJNN46JOUGV
      headerName: token
      # Possible values: HS256, HS384, HS512, NONE, corresponding to HmacSHA256, HmacSHA384, HmacSHA512, none
      algorithmId: HS256
      expiredAfterHours: 720
    xappAuth:
      # 跨应用操作acl的 com.dhl.fin.api，逗号分隔
      apiList: /com.dhl.fin.api/**
    apiVisitLogger:
      # 是否记录 com.dhl.fin.api 访问日志
      enabled: false
      # 不记录访问日志的 com.dhl.fin.api, 逗号分隔
      excludeApiList:
  # 异步方法相关配置
  asyncConfig:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 10000
    threadNamePrefix: ptp-
  cacheDefaultExpiration: 1
  performanceCounterLogger:
    # 是否记录 com.dhl.fin.api 调用耗时日志
    enabled: false
  ldap:
    host: ads.cn.dhl.com
    post: 389
  jwt:
    key: 123


logback:
  dir: logs
  maxfilesize: 100MB
  maxhistory: 180
  level: INFO
  filename:
    all: all
    info: info
    error: error
  isOpenConsole: true



custom:
  projectCode: stock_stk
  appVersions: FIN_BI-1.0,5iDHL_FIN-1.0,BOC-1.0,C_CAA-1.0,CSMS-1.0,CTI(FIN)-1.0,EAM-2.0,EasyVAT-2.0,GRE-1.0,IAS_DDU_Rpt-2.0,IBDP-1.0,IBPS-1.0,ICON-1.0,PPWK-1.0,PTP-1.0,RPMP-1.0,RTMT-1.0,TFS-1.0,TM1-1.0,VCS-5.0,PRS-1.0,CAC_EINV-1.0,EINV_Aisino-2.0,CREST-1.0,SAP-1.0,GWS_ADC-1.0,GWS_Gweb+-1.0,GWS_Gweb1.0-1.0,GWS_Gweb1.5-1.0,GWS_IRM-1.0,GWS_MIR-1.0,GWS_GMD-1.0,GWS_GLDET2-1.0,Basware-1.0,IBS+-1.0,IRIS-1.0,IBBR-1.0,EXPRESS,BI,EXPRESS BI START-1.0,SPLUNK-1.0,TPCX-1.0,DCGFINFW-1.0,Tradeshift-1.0,GetLean-1.0,RpaRK-1.0,FINTP_IIP-1.0,Express_TM1-1.0









